import type { BillingAccountDocument } from './billingTypes.js';

/** Test accounts keyed by last four digits (1234 … 6789). */
export const TEST_BILLING_ACCOUNTS: BillingAccountDocument[] = [
  {
    accountLastFour: '1234',
    customerName: 'Jordan Lee',
    plan: 'NovaTel Unlimited 50',
    monthlyCharge: 79.99,
    billMonth: '2026-05',
    recentCharges: [
      { description: 'Monthly plan fee', amount: 79.99, date: '2026-05-01' },
      { description: 'Monthly plan fee (duplicate)', amount: 79.99, date: '2026-05-01' },
      { description: 'Device installment', amount: 15.0, date: '2026-05-01' },
    ],
    duplicateChargeFlag: true,
    lateFeeOnAccount: 0,
    contractEndDate: '2026-11-01',
    underContract: true,
    earlyTerminationFee: 120,
    status: 'active',
    payments: [
      {
        initiatedDate: '2026-04-28',
        postedDate: '2026-04-29',
        amount: 94.99,
        status: 'posted',
      },
    ],
  },
  {
    accountLastFour: '2345',
    customerName: 'Sam Rivera',
    plan: 'NovaTel Basic 30',
    monthlyCharge: 49.99,
    billMonth: '2026-05',
    recentCharges: [
      { description: 'Monthly plan fee (incorrect tier)', amount: 89.99, date: '2026-05-01' },
      { description: 'International roaming', amount: 12.0, date: '2026-05-03' },
    ],
    duplicateChargeFlag: false,
    lateFeeOnAccount: 0,
    contractEndDate: '2026-08-15',
    underContract: true,
    earlyTerminationFee: 100,
    status: 'active',
    payments: [
      {
        initiatedDate: '2026-04-30',
        postedDate: '2026-05-01',
        amount: 49.99,
        status: 'posted',
      },
    ],
  },
  {
    accountLastFour: '3456',
    customerName: 'Taylor Brooks',
    plan: 'NovaTel Family 40',
    monthlyCharge: 59.99,
    billMonth: '2026-05',
    recentCharges: [
      { description: 'Monthly plan fee', amount: 59.99, date: '2026-05-01' },
      { description: 'Late payment fee', amount: 10.0, date: '2026-05-02' },
    ],
    duplicateChargeFlag: false,
    lateFeeOnAccount: 10.0,
    contractEndDate: null,
    underContract: false,
    earlyTerminationFee: 0,
    status: 'active',
    payments: [
      {
        initiatedDate: '2026-04-29',
        postedDate: '2026-05-02',
        amount: 59.99,
        status: 'posted',
      },
    ],
  },
  {
    accountLastFour: '4567',
    customerName: 'Morgan Chen',
    plan: 'NovaTel Unlimited 50',
    monthlyCharge: 79.99,
    billMonth: '2026-05',
    recentCharges: [
      { description: 'Monthly plan fee', amount: 79.99, date: '2026-05-01' },
      { description: 'Device installment', amount: 25.0, date: '2026-05-01' },
    ],
    duplicateChargeFlag: false,
    lateFeeOnAccount: 0,
    contractEndDate: '2027-03-15',
    underContract: true,
    earlyTerminationFee: 150,
    status: 'active',
    payments: [
      {
        initiatedDate: '2026-04-27',
        postedDate: '2026-04-28',
        amount: 104.99,
        status: 'posted',
      },
    ],
  },
  {
    accountLastFour: '5678',
    customerName: 'Casey Nguyen',
    plan: 'NovaTel Basic 30',
    monthlyCharge: 49.99,
    billMonth: '2026-05',
    recentCharges: [{ description: 'Monthly plan fee', amount: 49.99, date: '2026-05-01' }],
    duplicateChargeFlag: false,
    lateFeeOnAccount: 0,
    contractEndDate: '2025-01-01',
    underContract: false,
    earlyTerminationFee: 0,
    status: 'active',
    payments: [
      {
        initiatedDate: '2026-04-30',
        postedDate: '2026-05-01',
        amount: 49.99,
        status: 'posted',
      },
    ],
  },
  {
    accountLastFour: '6789',
    customerName: 'Riley Patel',
    plan: 'NovaTel Unlimited 50',
    monthlyCharge: 79.99,
    billMonth: '2026-05',
    recentCharges: [
      { description: 'Monthly plan fee', amount: 79.99, date: '2026-05-01' },
      { description: 'Late payment fee', amount: 10.0, date: '2026-05-05' },
    ],
    duplicateChargeFlag: false,
    lateFeeOnAccount: 10.0,
    contractEndDate: '2026-09-01',
    underContract: true,
    earlyTerminationFee: 120,
    status: 'past_due',
    payments: [
      {
        initiatedDate: '2026-05-01',
        postedDate: null,
        amount: 79.99,
        status: 'pending',
      },
    ],
  },
];
