#!/usr/bin/env bash
# Print Render deploy link and env vars to paste during blueprint setup.
set -euo pipefail
cd "$(dirname "$0")/.."

REPO_URL="${RENDER_REPO_URL:-https://github.com/Karan-returns/VoiceAI}"

if [[ ! -f .env ]]; then
  echo "Missing dashboard/.env — set MONGODB_URI first."
  exit 1
fi

# shellcheck disable=SC1091
source .env

if [[ -z "${MONGODB_URI:-}" ]]; then
  echo "MONGODB_URI is required in .env"
  exit 1
fi

cat > render-env-paste.txt <<EOF
# Paste MONGODB_URI when Render Blueprint asks for environment variables.
# DASHBOARD_API_KEY is auto-generated by Render (find it under Environment after deploy).

MONGODB_URI=${MONGODB_URI}
EOF

echo "=== Render one-click deploy ==="
echo ""
echo "1. Open:"
echo "   https://dashboard.render.com/select-repo?type=blueprint"
echo ""
echo "2. Connect GitHub repo: Karan-returns/VoiceAI"
echo ""
echo "3. When prompted for MONGODB_URI, paste the value from:"
echo "   $(pwd)/render-env-paste.txt"
echo ""
echo "4. After deploy (~5 min), open your service URL and use DASHBOARD_API_KEY from:"
echo "   Render Dashboard → novatel-qa-dashboard → Environment"
echo ""
echo "Direct blueprint link (after code is pushed to GitHub):"
echo "   https://render.com/deploy?repo=${REPO_URL}"
